# This file provides explicit build settings for Netlify...

[build]
  # Command to build the React app
  command = "npm run build"
  
  # Directory that contains the built site
  publish = "build/"
  
  # Directory where the serverless functions are located
  functions = "netlify/functions/"

[functions]
  # Set the timeout for all functions to 26 seconds
  timeout = 26

